### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GoobyMain** [catornot/TitanFall-2-mods#5]
**Mod**
AutoGG

**Describe the bug**
The Automessage.cfg file never gets executed, something is wrong with the code that's supposed to execute it in the AutoMessage.nut script

**To Reproduce**
I delete and redownload the mod, go into the .cfg file and change the message to anything other than "gg"
Launch Northstar, play a game, at the end, it automatically puts in chat "gg"
open console, run "exec AutoMessage"
play another game, at the end, it automatically puts what is in the .cfg file

If instead of editing the .cfg file I edit the default value of the ConVar in the mod.json file, it shows in chat how I want at the end of the game, but the .cfg file still does nothing

**Screenshots**

**Comment by catornot** [comment]
lol
the mod never actually runs  `exec AutoMessage`

**Comment by GoobyMain** [comment]
is it not supposed to or is it a mistake?
